name: GitHub Actions Demo
on: [push]
jobs:
  hello_world_job:
    runs-on: [self-hosted, Linux, X64]
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: 864141050364.dkr.ecr.ap-southeast-2.amazonaws.com
          ECR_REPOSITORY: anthonygithub
          IMAGE_TAG: ${{ github.sha }}
        run: |
          /kaniko/executor --force --dockerfile=Dockerfile --context=./hello-world-docker-action --destination=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./hello-world-docker-action/task-definition.json
          container-name: ecs-devops-sandbox
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ecs-devops-sandbox-service
          cluster: anthonygithub
          wait-for-service-stability: true
